services:
  journal-backend:
    build:
      context: .
      tags:
        - pbrojas-journal-backend:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}